package joaopaulo.com.br.queheroisoueu.historias;

/**
 * Created by minerthal on 07/04/17.
 */

public class Historias {

    public String retornaHistoria(int i){
        String[] historias = new String[7];
        historias[0] = "O Hulk, por vezes referido como O Incrível Hulk (The Incredible Hulk, no original em inglês) é um personagem de quadrinhos/banda desenhada do gênero super-herói, propriedade da Marvel Comics, editora pela qual as histórias do personagem são publicados desde sua criação, nos anos 1960. Concebido pelo roteirista Stan Lee (1922-) e pelo desenhista Jack Kirby (1917-1994), teve sua primeira aparição junto ao público original dos Estados Unidos na revista The Incredible Hulk n°1, lançada no mercado americano pela Marvel Comics em maio de 1962, um título solo do personagem, garantindo-lhe o acesso ao que mais tarde seria popularmente conhecido como Universo Marvel dos quadrinhos/banda desenhada. A partir de então, o Hulk tem aparecido, protagonizando ou não, diversas histórias da editora, se tornando um dos mais visualmente reconhecíveis da mesma, tendo o universo entorno do personagem se expandido continuadamente ao longo das últimas décadas.Apesar de fugir de diversos padrões pré-estabelecidos para super-heróis enquanto personagem da cultura pop mundial, Hulk é considerado um super-herói, mais pelas características sobre-humanas por ele apresentadas do que por conceitos bases de inserção no gênero. ";
        historias[1] = "Thor é o deus pagão nórdico, dos trovões e das batalhas. Pertence ao clã dos deuses Æsir, e é filho do deus Odin.Thor usa como arma o martelo Mjolnir, e tem o cinto Megingjord, que lhe confere enormes forças. Está associado aos trovões, relâmpagos, tempestades, árvores de carvalho, força, proteção da humanidade e também a santificação, cura e fertilidade.";
        historias[2] = "Superman ou Super-homem é um super-herói fictício de história em quadrinhos americanas publicado pela DC Comics, uma empresa subsidiária do grupo Time Warner. Superman, entretanto, já foi adaptado para diversos outros meios desde os anos 1930, como cinema, rádio, televisão, literatura e Video game. Superman é um super-herói criado pela dupla de autores de quadrinhos Joe Shuster e Jerry Siegel. Sua primeira aparição foi apresentada na revista Action Comics #1 em 1938, nos Estados Unidos. O personagem nasceu no fictício planeta Krypton e foi chamado pelos seus pais de Kal-El (que significaria Filho das Estrelas no idioma kryptoniano). Foi mandado à Terra por seu pai, Jor-El, um cientista, momentos antes do planeta explodir. O foguete aterrissou na Terra na cidade de Smallville (por alguns anos, foi traduzida no Brasil como Pequenopolis), onde o jovem Kal-El foi descoberto pelo casal de fazendeiros Jonathan e Martha Kent. Conforme foi crescendo, ele descobriu que tinha habilidades diferentes dos humanos. Quando não está com o tradicional uniforme azul e vermelho, ele vive como Clark Kent, repórter profissional no Planeta Diário (Estrela Diária em Portugal).";
        historias[3] = "O Homem-Aranha (Spider-Man no original em inglês) alter-ego de Peter Parker, é um personagem fictício, um super-herói que aparece nas revistas em quadrinhos (banda desenhada em Portugal) americanas publicadas pela Marvel Comics, existindo no seu universo partilhado. O Homem-Aranha foi criado pelo editor/escritor Stan Lee e pelo escritor/artista Steve Ditko, e a sua primeira aparição foi no livro de antologia Amazing Fantasy #15 (Agosto de 1962), durante a Era de Prata da banda desenhada. Lee e Ditko conceberam o personagem como um órfão, que foi educado e criado pela sua Tia May e o seu Tio Ben, e, enquanto adolescente, tem de lidar com as lutas diárias normais da sua idade, em adição àquelas que tem como combatente do crime mascarado. Para combater os seus inimigos, os criadores deram-lhe super força e agilidade, a habilidade de conseguir aderir na maior parte das superfícies, a possibilidade de disparar teias de aranha através de mecanismos montados nos pulsos (inventados por ele próprio, a que ele chama lança-teia - web-shooters) e consegue reagir precognitivamente ao perigo com o seu sentido-aranha (spider-sense). Os seus poderes foram adquiridos após ter sido mordido por uma aranha radioativa.";
        historias[4] = "Quando Scott era uma criança crescendo em Los Angeles, Califórnia, Estados Unidos, ele tinha 10 anos era o irmão mais velho e tinha seu irmão mais novo Alexander (Alex) Summers, futuramente conhecido como Destrutor, seu pai, o Major Christopher Summers da Força Aérea dos Estados Unidos, levou sua família em um voo com seu avião, para a casa dos avós de Scott no Alaska, o avião foi atacado por uma nave alienígena Shi'ar, sua mãe Katherine Anne Summers sabia que só tinha 2 paraquedas, então enquanto o avião caía em chamas, os pais de Scott prenderam-no e a seu irmão mais novo Alex em um paraquedas e empurraram-nos do avião, na esperança de que eles sobrevivessem. Infelizmente o paraquedas pegou fogo e Scott bateu a cabeça na aterrissagem, no mesmo momento o avião explode, sem deixar vestígios sobre o paradeiro dos seus pais que na verdade foram abduzidos pela nave alienígena. Esse acidente causou danos no cérebro de Scott, responsáveis por sua inabilidade em controlar seus raios ópticos, assim como por uma prolongada amnésia sobre sua infância, depois dos dois ficaram hospitalizados, os meninos são levados para um orfanato em Nebraska, dirigido por Michael Milbury, que na verdade era ninguém menos do que o vilão Sr. Sinistro disfarçado.";
        historias[5] = "O cientista, inventor, engenheiro e gênio tecnológico, Donatello usa uma máscara roxa e empunha uma Bō . Donatello é, talvez, a tartaruga menos violenta, preferindo usar seu conhecimento para resolver os conflitos, mas nunca hesita em defender seus irmãos. Ele foi nomeado após o artista renascentista e escultor italiano de Florença, Donatello.";

        return historias[i];
    }
}
